import soleira from '/screenshots/social_media.png';
import viva from '/screenshots/newsletter.png';
import review from '/screenshots/reviews.png';
import resume from '/screenshots/resume.png';
import happy from '/screenshots/happy.png';
import matcha from '/screenshots/matcha.png';
import dndbot from '/screenshots/dndbot.png';
import type { Project } from './project';

export const projects: Project[] = [
  {
    name: 'Soleira Lounge',
    subtitle: 'Full-Stack Social Platform',
    briefDescription:
      'Full production social platform with user auth, real-time messaging (1000s of messages), notifications, and content management. Demonstrates database architecture, security, and scalable API design.',
    fullDescription: '/new-portfolio-frontend/markdown/soleira.md',
    githubLink: 'https://github.com/asseternity/messenger-frontend',
    demoLink: 'https://asseternity.github.io/messenger-frontend/',
    screenshotPath: soleira,
    tags: [
      'TypeScript',
      'JavaScript',
      'Node.js',
      'React',
      'Tailwind CSS',
      'shadcn/ui',
      'Vite',
      'Express',
      'REST APIs',
      'Auth',
      'SQL',
      'PostgreSQL',
      'Prisma ORM',
      'Vitest',
      'TDD',
      'Git',
      'CI/CD',
    ],
  },
  {
    name: 'Viva Verso',
    subtitle: 'Blog / Newsletter CMS',
    briefDescription:
      'Dual-frontend system (public + admin) featuring authentication, CRUD operations, and dynamic content workflows. Emphasizes maintainability and modular patterns.',
    fullDescription: '/new-portfolio-frontend/markdown/viva.md',
    githubLink: 'https://github.com/asseternity/c5-personal-react',
    demoLink: 'https://asseternity.github.io/c5-personal-react/',
    screenshotPath: viva,
    tags: [
      'TypeScript',
      'JavaScript',
      'Node.js',
      'React',
      'Tailwind CSS',
      'shadcn/ui',
      'Vite',
      'Express',
      'REST APIs',
      'Auth',
      'SQL',
      'PostgreSQL',
      'Prisma ORM',
      'Vitest',
      'TDD',
      'Git',
      'CI/CD',
    ],
  },
  {
    name: 'What Makes Lands Happy',
    subtitle: 'Full-Stack Web App For Data Visualization + Analytics',
    briefDescription:
      'Integrates 18 global datasets through a Python data pipeline, exporting cleaned JSON to a TypeScript visualization app. Bridges frontend data viz with backend analytics.',
    fullDescription: '/new-portfolio-frontend/markdown/happy.md',
    githubLink: 'https://github.com/asseternity/what_makes_lands_happy',
    demoLink: 'https://asseternity.github.io/what_makes_lands_happy/',
    screenshotPath: happy,
    tags: [
      'TypeScript',
      'JavaScript',
      'Node.js',
      'React',
      'Tailwind CSS',
      'shadcn/ui',
      'Vite',
      'Express',
      'REST APIs',
      'Vitest',
      'TDD',
      'Git',
      'CI/CD',
      'Python',
      'pandas',
    ],
  },
  {
    name: 'Matcha Man Telegram Bot',
    subtitle: '',
    briefDescription:
      'Automated scraper bot monitoring matcha storefronts, featuring scheduling and command-driven interface. Demonstrates integrations and automation.',
    fullDescription: '/new-portfolio-frontend/markdown/matcha.md',
    githubLink:
      'https://github.com/asseternity/matcha-updater?tab=readme-ov-file#link-matchamanbot',
    demoLink: 'https://t.me/MatchaManBot',
    screenshotPath: matcha,
    tags: [
      'TypeScript',
      'JavaScript',
      'Node.js',
      'Vite',
      'Express',
      'REST APIs',
      'Vitest',
      'TDD',
      'Git',
      'CI/CD',
      'Telegram Bots',
    ],
  },
  {
    name: 'DND Witch Telegram Bot',
    subtitle: '',
    briefDescription:
      'Fantasy-themed bot built as a Dockerized ASP.NET service; shows .NET and deployment proficiency.',
    fullDescription: '/new-portfolio-frontend/markdown/dndbot.md',
    githubLink: 'https://github.com/asseternity/dnd-witch-backend',
    demoLink: 'https://t.me/DnDWitchBot',
    screenshotPath: dndbot,
    tags: [
      'REST APIs',
      'TDD',
      'Git',
      'CI/CD',
      'Docker',
      'C#',
      '.NET',
      'ASP.NET',
      'Telegram Bots',
      'Unity',
      'Godot',
      'Articy',
      'Blender',
    ],
  },
  {
    name: 'Machine Learning: Game Review Predictor',
    subtitle: '',
    briefDescription:
      'End-to-end ML pipeline predicting IGN review scores using scraped and enriched metadata. Highlights data preprocessing and model evaluation.',
    fullDescription: '/new-portfolio-frontend/markdown/review.md',
    githubLink: 'https://github.com/asseternity/predictive_data_science',
    demoLink:
      'ttps://www.kaggle.com/code/assetn/video-game-review-score-predictor',
    screenshotPath: review,
    tags: ['SQL', 'PostgreSQL', 'Git', 'CI/CD', 'Python', 'pandas', 'XGBoost'],
  },
  {
    name: 'Resume Dataset Analysis',
    subtitle: '',
    briefDescription:
      'Exploratory analysis of 54 000 resumes to map career transitions from law to tech. Demonstrates SQL-Python integration and visualization.',
    fullDescription: '/new-portfolio-frontend/markdown/resume.md',
    githubLink: 'https://github.com/asseternity/resume_data_analysis',
    demoLink: 'https://www.kaggle.com/code/assetn/resume-dataset-analysis',
    screenshotPath: resume,
    tags: ['SQL', 'PostgreSQL', 'Git', 'CI/CD', 'Python', 'pandas', 'XGBoost'],
  },
];
